#!/bin/bash

# bash_colors

# Setup color variables

c_black=""
c_blue=""
c_bold=""
c_cyan=""
c_green=""
c_orange=""
c_purple=""
c_red=""
c_reset=""
c_white=""
c_yellow=""

if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
    tput sgr0 # reset colors

    c_bold=$(tput bold)
    c_reset=$(tput sgr0)

    # Solarized colors
    # (https://github.com/altercation/solarized/tree/master/iterm2-colors-solarized#the-values)
    c_black=$(tput setaf 0)
    c_blue=$(tput setaf 33)
    c_cyan=$(tput setaf 37)
    c_green=$(tput setaf 64)
    c_orange=$(tput setaf 166)
    c_purple=$(tput setaf 125)
    c_red=$(tput setaf 124)
    c_white=$(tput setaf 15)
    c_yellow=$(tput setaf 136)
else
    c_bold="\x1B[1m"
    c_reset="\x1B[0m"

    c_black="\x1B[1;30m"
    c_blue="\x1B[1;34m"
    c_cyan="\x1B[1;36m"
    c_green="\x1B[1;32m"
    c_orange="\x1B[1;33m"
    c_purple="\x1B[1;35m"
    c_red="\x1B[1;31m"
    c_white="\x1B[1;37m"
    c_yellow="\x1B[1;33m"
fi

export c_black c_blue c_bold c_cyan c_green c_orange c_purple c_red c_reset c_white c_yellow