#!/bin/bash

# bash_profile

# By default, want group able to see files
umask 0002

# set 256 color profile where possible
if [[ $COLORTERM == gnome-* && $TERM == xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
    export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then
    export TERM=xterm-256color
fi

# Setup color variables
[ -r $HOME/.dotfiles/shell/bash_colors ] && source $HOME/.dotfiles/shell/bash_colors

# Up-front dotfiles configuration
# Not part of `load_dotfiles` because it must be sourced before anything else
# to be sure that commands like `brew` (when installed in a custom location)
# are already added to the PATH.
[ -r $HOME/.dotfilesrc ] && source $HOME/.dotfilesrc;

load_dotfiles() {
    declare -a files=(
        $HOME/.dotfiles/shell/bash_options # Options
        $HOME/.dotfiles/shell/bash_exports # Exports
        $HOME/.dotfiles/shell/bash_aliases # Aliases
        $HOME/.dotfiles/shell/functions/* # Functions
        $HOME/.dotfiles/shell/bash_prompt # Custom bash prompt
        $HOME/.dotfiles/shell/bash_paths # Path modifications
        $HOME/.bash_profile.local # Local and private settings not under version control (e.g. git credentials)
    )

    # if these files are readable, source them
    for index in ${!files[*]}
    do
        if [[ -r ${files[$index]} ]]; then
            source ${files[$index]}
        fi
    done
}

load_dotfiles
unset load_dotfiles

# Localize git configuration

# Setup git based on locally defined environment
if [ $(type -P git) ]; then
	# Setup proxy if defined
	[ "$http_proxy" ] && git config --global http.proxy $http_proxy
	
	git config --global user.name "Ken Brucker"
fi
##
# Your previous /Users/ken/.bash_profile file was backed up as /Users/ken/.bash_profile.macports-saved_2014-10-16_at_16:36:16
##

# MacPorts Installer addition on 2014-10-16_at_16:36:16: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.


##
# Your previous /Users/ken/.bash_profile file was backed up as /Users/ken/.bash_profile.macports-saved_2015-07-02_at_10:44:37
##

# MacPorts Installer addition on 2015-07-02_at_10:44:37: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.

