#!/bin/bash

# bash_paths

# ========
# = PATH =
# ========

# Directories to be prepended to PATH
declare -a dirs_to_prepend=(
    "/usr/local/bin" # Ensure that this bin always takes precedence over `/usr/bin`
	"/opt/local/bin" # Same for this one
	"/opt/local/sbin" # And this one
)

# Directories to be appended to PATH
declare -a dirs_to_append=(
    "$HOME/bin"
    "$HOME/.dotfiles/bin"
)

# Prepend directories to PATH
for index in ${!dirs_to_prepend[*]}
do
    if [ -d ${dirs_to_prepend[$index]} ]; then
        # If these directories exist, then prepend them to existing PATH
        PATH="${dirs_to_prepend[$index]}:$PATH"
    fi
done

# Append directories to PATH
for index in ${!dirs_to_append[*]}
do
    if [ -d ${dirs_to_append[$index]} ]; then
        # If these bins exist, then append them to existing PATH
        PATH="$PATH:${dirs_to_append[$index]}"
    fi
done

unset dirs_to_prepend dirs_to_append

export PATH


# ===========
# = MANPATH =
# ===========

# Directories to be appended to MANPATH
declare -a dirs_to_append=(
	"/opt/local/man"
	"/usr/local/man"
	"/usr/local/share/man"
)

# Append directories to MANPATH
for index in ${!dirs_to_append[*]}
do
    if [ -d ${dirs_to_append[$index]} ]; then
        # If these bins exist, then append them to existing MANPATH
        MANPATH="$MANPATH:${dirs_to_append[$index]}"
    fi
done

unset dirs_to_append

export MANPATH

# ============
# = PERL5LIB =
# ============

# Perl5 Library locations
declare -a dirs_to_append=(
	"$HOME/Library/Perl"
	"/opt/local/lib/perl5"
)

# Append directories to PERL5LIB
for index in ${!dirs_to_append[*]}
do
    if [ -d ${dirs_to_append[$index]} ]; then
        # If these bins exist, then append them to existing MANPATH
        PERL5LIB="$PERL5LIB:${dirs_to_append[$index]}"
    fi
done

unset dirs_to_append

export PERL5LIB
