#!/bin/bash

# bashrc

# For interactive shells, source profile
[ -n "$PS1" ] && source ~/.bash_profile

# For non-interactive shells, setup paths
[ -z "$PS1" ] && source ~/.dotfiles/shell/bash_paths

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Add Rustup environment if available
[ -f "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"
