#!/bin/bash

# bash_config

# Use dotfile script as the default editor - Points at textmate
export EDITOR="~/.dotfiles/bin/editor"

# Ignore duplicate commands in the history
export HISTCONTROL=ignoredups

# Increase the maximum number of lines contained in the history file
# (default is 500)
export HISTFILESIZE=10000

# Increase the maximum number of commands to remember
# (default is 500)
export HISTSIZE=10000

# Make some commands not show up in history
export HISTIGNORE="ls:ls *:cd:cd -:pwd;exit:date:* --help"

# Don't clear the screen after quitting a manual page
export MANPAGER="less -X"

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# For TextMate - Setup Locale info
export LC_CTYPE=en_US.UTF-8

# Turn on colors in terminal
export CLICOLOR=1
