#!/bin/bash

# bash_config

# Shortcut for dotfile bin directory
export DOTBIN="$HOME/.dotfiles/bin"

# Use dotfile script as the default editor - Points at textmate
export EDITOR="$HOME/.dotfiles/bin/editor"

# Ignore duplicate commands or lines starting with space in the history
export HISTCONTROL=ignoreboth

# Increase the maximum number of lines contained in the history file
# (default is 500)
export HISTFILESIZE=10000

# Increase the maximum number of commands to remember
# (default is 500)
export HISTSIZE=10000

# Make some commands not show up in history
export HISTIGNORE="ls:cd:cd -:pwd;exit:date:* --help"

# Don't clear the screen after quitting a manual page
export MANPAGER="less -X"

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# For TextMate - Setup Locale info
export LC_CTYPE=en_US.UTF-8

# Turn on colors in terminal
export CLICOLOR=1

# Location of Wordpress files for phpunit testing
export WP_TESTS_DIR=${HOME}/tmp/wordpress-tests-lib

# Where is the WP core installed?
export WP_CORE_DIR=${HOME}/tmp/wordpress

# IP address of remote when logged in via SSH
if [ "$SSH_CLIENT" != "" ]; then
	export HOMEIP=`echo $SSH_CLIENT | awk '{ print $1 }'`
fi

# Enable logging of aqbanking commands to /tmp/ofx.log
# WARNING - Can expose passwords!!!
# export AQOFX_LOG_COMM=1