#!/bin/bash

# bash_paths

# ARG1 = ':' separated list of data
# ARG2 = item to filter from ':' separated list
filter_list() {
	text=$1
    text=${text//":$2:"/:} #delete all instances in the middle
    text=${text/%":$2"/} #delete any instance at the end
    text=${text/#"$2:"/} #delete any instance at the beginning	
	echo "$text" # Return result
}

# ARG1 = variable name
# ARG2 = items to add to colon separated list
prepend_list() {
	local var_name=$1
	declare -a prepend_array=("${!2}")
	
	for index in ${!prepend_array[*]}
	do
	    if [ -d ${prepend_array[$index]} ]; then
	        # If these directories exist, then prepend them to existing
			eval $var_name=$(filter_list "${!var_name}" ${prepend_array[$index]}) # Filter out directory if already in list
	        eval $var_name="${prepend_array[$index]}${!var_name:+":${!var_name}"}"
	    fi
	done
}

# ARG1 = variable name
# ARG2 = items to add to colon separated list
append_list() {
	local var_name=$1
	declare -a append_array=("${!2}")
	
	for index in ${!append_array[*]}
	do
	    if [ -d ${append_array[$index]} ]; then
	        # If these directories exist, then append them to existing
			eval $var_name=$(filter_list "${!var_name}" ${append_array[$index]}) # Filter out directory if already in list
	        eval $var_name="${!var_name:+"${!var_name}:"}${append_array[$index]}"
	    fi
	done
}


# ========
# = PATH =
# ========

# Directories to be prepended to PATH
declare -a dirs_to_prepend=(
    "/usr/local/bin" # Ensure that this bin always takes precedence over `/usr/bin`
	"/opt/local/bin" # Same for this one
	"/opt/local/sbin" # And this one
)

prepend_list PATH dirs_to_prepend[@]

# Directories to be appended to PATH
declare -a dirs_to_append=(
    "$HOME/bin"
    "$HOME/.dotfiles/bin"
)

append_list PATH dirs_to_append[@]
unset dirs_to_prepend dirs_to_append

export PATH

# ===========
# = MANPATH =
# ===========

# Directories to be appended to MANPATH
declare -a dirs_to_append=(
	"/opt/local/man"
	"/usr/local/man"
	"/usr/local/share/man"
)

append_list MANPATH dirs_to_append[@]

unset dirs_to_append

export MANPATH

# ============
# = PERL5LIB =
# ============

# Perl5 Library locations
declare -a dirs_to_append=(
	"$HOME/Library/Perl"
	"/opt/local/lib/perl5"
)

append_list PERL5LIB dirs_to_append[@]

unset dirs_to_append

export PERL5LIB

# Cleanup

unset prepend_list
unset append_list