#!/bin/zsh
# zlogin
#
# Zsh configuration files in order of execution:
#   all users      user       login shell  interactive shell  scripts  Terminal.app
#   /etc/zshenv    .zshenv    √            √                  √        √
#   /etc/zprofile  .zprofile  √            x                  x        √
#   /etc/zshrc     .zshrc     √            √                  x        √
#   /etc/zlogin    .zlogin    √            x                  x        √
#   /etc/zlogout   .zlogout   √            x                  x        √

if [[ -r ${HOME}/.zlogin.local ]]; then
	source ${HOME}/.zlogin.local
fi

if type fortune > /dev/null; then
	if type cowsay > /dev/null; then
		COWSAY="| cowsay"
	fi
	if type lolcat > /dev/null; then
		LOLCAT="| lolcat"
	fi

	eval "fortune $COWSAY $LOLCAT "
	unset COWSAY LOLCAT
fi
