# zprofile
#
# Zsh configuration files in order of execution:
#   all users      user       login shell  interactive shell  scripts  Terminal.app
#   /etc/zshenv    .zshenv    √            √                  √        √
#   /etc/zprofile  .zprofile  √            x                  x        √
#   /etc/zshrc     .zshrc     √            √                  x        √
#   /etc/zlogin    .zlogin    √            x                  x        √
#   /etc/zlogout   .zlogout   √            x                  x        √

# Setup brew
if [ -f /opt/homebrew/bin/brew ]; then
	eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# Display a fortune if configured
if type fortune > /dev/null; then
	if type cowsay > /dev/null; then
		COWSAY="| cowsay -W80"
	fi
	if type lolcat > /dev/null; then
		LOLCAT="| lolcat"
	fi

	eval "fortune $COWSAY $LOLCAT "
	unset COWSAY LOLCAT
fi

# vim: filetype=zsh
