#!/bin/zsh
#
# zsh_colors
#
# 256-color Cheatsheet: https://www.ditig.com/256-colors-cheat-sheet
#
# See https://unix.stackexchange.com/a/408871 for details on zsh colors
#
# Colors setup by Oh-my-zsh
#

