#!/bin/bash

run_brew() {

	# Check for Homebrew
	if type_exists 'brew'; then
		e_header "Updating Homebrew..."
		# Use the latest version of Homebrew
		brew update
		[[ $? ]] && e_success "Done"

		e_header "Updating any existing Homebrew formulae..."
		# Upgrade any already-installed formulae
		brew upgrade
		[[ $? ]] && e_success "Done"

		e_header "Checking status of desired Homebrew formulae..."
		local list_formulae
		local -a missing_formulae
		local -a desired_formulae=(
			'carthage' # Swift Library Dependency Manager
			'composer'
			'coreutils' # GNU core utilities (those that come with OS X are outdated)
			'cowsay' # Just like it says... have some cowsay fun
			'exiftool'
			'git'
			'jq' # CLI JSON processor
			'mariadb'
			'mercurial'
			'node'
			'php'
			'pyenv'
			'sass/sass/sass'
			'swiftgen' # Swift Code Generation tool
			'telnet'
			'tmux' #Terminal Mux
			'wget'
			'wp-cli'
		)

		for index in ${!desired_formulae[*]}
		do
			if ! formula_exists ${desired_formulae[$index]}; then
				# Store the name (and options) of every missing formula
				missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
			fi
		done

		if [[ "$missing_formulae" ]]; then
			# Convert the array of missing formula into a list of space-separate strings
			list_formulae=$( printf "%s " "${missing_formulae[@]}" )

			e_header "Installing missing Homebrew formulae... $list_formulae"
			# Install all missing formulae
			if ! brew install $list_formulae ; then
				e_error "Brew install failed"
				exit 1
			fi

			e_success "Done"
		fi

		# use latest rsync rather than out-dated OS X rsync
		# install separately from the main formulae list to fix gh-19
		# brew install https://raw.github.com/Homebrew/homebrew-dupes/master/rsync.rb

		# Remove outdated versions from the Cellar
		brew cleanup
	else
		printf "\n"
		e_error "Error: Homebrew not found."
		printf "Aborting...\n"
		exit 1
	fi

}
