#!/bin/bash

# TODO Update installed SW list

run_list() {

cat <<EOT
OS X dotfiles - Ken Brucker

Additional software to install

golang
go get github.com/mattn/efm-langserver
pip install vim-vint

Browsers:

Development:
  Xcode
  iTerm2
	
Other:
	1Password
	Dropbox
EOT

}
