#!/bin/bash

# TODO Update installed SW list

run_list() {

cat <<EOT
OS X dotfiles - Ken Brucker

Additional software to install

Development:
  Xcode
  iTerm2

% # Needed for language server -- installed via brew on OSX
% golang
% # language server for vim
% go get github.com/mattn/efm-langserver
% # vi linter
% pip install vim-vint # Available via brew
% # universal-ctags (for gutentags)
% brew install --HEAD universal-ctags/universal-ctags/universal-ctags

Other:
	1Password
	Dropbox

Ubuntu/Fedora:
- npm # includes nodejs
- zsh
- util-linux-user # for chsh
- exuberant-ctags # Possibly called ctags
- fzf
- ShellCheck
- golang
- sqlite
- Build apropos

vim:
  :helptags ALL

tmux:
  # Install plugins
  <f2>I

EOT

}
