#!/bin/bash
#
# Mirror dot files into home directory

link() {
	# If target is a link to a directory, remove it before linking.
	# Otherwise bail outta here with a warning
	if [ -d "${HOME}/${2}" ]; then
		if [ ! -L "${HOME}/${2}" ]; then
			e_warning "${HOME}/${2} is a directory, skipping link $1 => $2"
			return
		fi

		rm "${HOME}/${2}"
	fi

	# Make a backup of real file before trashing it
	backup_file "${HOME}/${2}"

  # Force create/replace the symlink.
	ln -fs "${DOTFILES}/${1}" "${HOME}/${2}"
}

mirror_files() {
	# Force remove the vim directory if it's already there.
	if [ -d "${HOME}/.vim" ] && [ ! -L "${HOME}/.vim" ]; then
		rm -rf "${HOME}/.vim"
	fi

	# Create the necessary symbolic links between the `.dotfiles` and `HOME`
	# directory. The `bash_profile` sources other files directly from the
	# `.dotfiles` repository.
	link "shell/bashrc"				         	".bashrc"
	link "shell/bash_profile"		      	".bash_profile"
	link "shell/bash_logout"			      ".bash_logout"
	link "shell/curlrc"				   	      ".curlrc"
	link "shell/inputrc"			        	".inputrc"
	link "shell/p10k.zsh"			        	".p10k.zsh"
	link "shell/zshenv"					        ".zshenv"
	link "shell/zprofile"				        ".zprofile"
	link "shell/zshrc"					        ".zshrc"
	link "shell/zlogin"					        ".zlogin"
	link "shell/tmux.conf"			      	".tmux.conf"
	link "gdb/gdbinit"                  ".gdbinit"
	link "mercurial/hgignore.defaults"	".hgignore.defaults"
	link "vim"							            ".vim"
	link "vim/gvimrc"					          ".gvimrc"
	link "vim/vimrc"				          	".vimrc"
	link "shell/vintrc.yaml"            ".vintrc.yaml"
	link "config/alacritty" 						".config/alacritty"
	link "config/bat"    								".config/bat"
	link "config/cheat"    						  ".config/cheat"
	link "config/ctags"                 ".config/ctags"
	link "config/efm-langserver"        ".config/efm-langserver"
	link "config/ghostty"               ".config/ghostty"
	link "config/git"                   ".config/git"
	link "config/kitty"                 ".config/kitty"

	e_success "Dotfiles update complete!"
}
