#!/bin/bash
#
# Mirror dot files into home directory

link() {
	# If target is a link to a directory, remove it before linking.
	# Otherwise bail outta here with a warning
	if [ -d "${HOME}/${2}" ]; then
		if [ ! -L "${HOME}/${2}" ]; then
			e_warning "${HOME}/${2} is a directory, skipping link $1 => $2"
			return
		fi

		rm "${HOME}/${2}"
	fi

	# Make a backup of real file before trashing it
	backup_file "${HOME}/${2}"

  # Force create/replace the symlink.
	ln -fs "${DOTFILES}/${1}" "${HOME}/${2}"
}

mirror_git() {
	# Copy `.gitconfig`.
	# Any global git commands in `~/.shell_profile.local` will be written to
	# `.gitconfig`. This prevents them being committed to the repository.
	#
	# gitconfig.private provides a template for the global .gitconfig
	: "${VCS_AUTHOR_NAME:?must be set}"
	: "${VCS_AUTHOR_EMAIL:?must be set}"
	backup_file "${HOME}/.gitconfig"
	cp -p "${DOTFILES}/git/gitconfig.private"  "${HOME}/.gitconfig"
	git config --global user.name "$VCS_AUTHOR_NAME"
	git config --global user.email "$VCS_AUTHOR_EMAIL"
}

mirror_files() {
	mirror_git

	# Force remove the vim directory if it's already there.
	if [ -d "${HOME}/.vim" ] && [ ! -L "${HOME}/.vim" ]; then
		rm -rf "${HOME}/.vim"
	fi

	# Create the necessary symbolic links between the `.dotfiles` and `HOME`
	# directory. The `bash_profile` sources other files directly from the
	# `.dotfiles` repository.
	link "shell/bashrc"				         	".bashrc"
	link "shell/bash_profile"		      	".bash_profile"
	link "shell/bash_logout"			      ".bash_logout"
	link "shell/curlrc"				   	      ".curlrc"
	link "shell/inputrc"			        	".inputrc"
	link "shell/zshenv"					        ".zshenv"
	link "shell/zprofile"				        ".zprofile"
	link "shell/zshrc"					        ".zshrc"
	link "shell/zlogin"					        ".zlogin"
	link "shell/tmux.conf"			      	".tmux.conf"
	link "git/gitattributes"			      ".gitattributes"
	link "git/gitignore"				        ".gitignore_global"
	link "mercurial/hgignore.defaults"	".hgignore.defaults"
	link "vim"							            ".vim"
	link "vim/gvimrc"					          ".gvimrc"
	link "vim/vimrc"				          	".vimrc"
	link "shell/vintrc.yaml"            ".vintrc.yaml"
	link "config/efm-langserver"        ".config/efm-langserver"
	link "config/ctags"                 ".config/ctags"
	link "config/kitty"                 ".config/kitty"

	e_success "Dotfiles update complete!"
}
