#!/bin/bash

run_npm() {

    # Check for npm
    if type_exists 'npm'; then
        e_header "Installing Node.js packages..."

        # List of npm packages
		# TODO Want any node packages?
        # local packages="bower gify grunt-cli jshint karma yo"
		local packages=""

		if [[ "" != $packages ]]; then
			# Install packages globally and quietly
			npm install $packages --global --quiet
		else
			echo "- Nothing to install"
		fi

        [[ $? ]] && e_success "Done"
    else
        printf "\n"
        e_error "Error: npm not found."
        printf "Aborting...\n"
        exit
    fi

}
