#!/bin/bash

run_npm() {

    # Check for npm
    if type_exists 'npm'; then
        e_header "Installing Node.js packages..."

			if [ -w /usr/local/lib ]; then
  			# Globally instally node packages
  			local -a packages=(
  			  "tiddlywiki"
  			)

  			for pkg in "${packages[@]}" ; do
  				# Install packages globally and quietly
  				if ! npm_pkg_exists $pkg ; then
    				if ! npm install $pkg --global --quiet ; then
	  			  	e_error "npm install failed"
	  			  	exit 1
	  				fi
	  			fi
	  		done
			else
				e_error "No write access to /usr/local/lib - skipping global node packages"
			fi

			echo "Installing coc.nvim extensions ..."

			local -a packages=(
				'coc-cmake'
			  'coc-git'
				'coc-json'
				'coc-sh'
				'coc-snippets'
			)

			# coc.nvim packages are installed locally in ~/.config/coc/extensions
			local save_dir=`pwd`
			mkdir -p ~/.config/coc/extensions
			cd ~/.config/coc/extensions
			if [ ! -f package.json ]
			then
				echo '{"dependencies":{}}' > package.json
			fi

			for pkg in "${packages[@]}"
			do
				if ! npm_pkg_exists $pkg ; then
					if ! npm install $pkg --global-style --ignore-scripts --no-bin-links --no-package-lock --omit=dev ; then
						e_error "npm install failed"
						exit 1
					fi
				fi
			done
			cd $save_dir

    else
        printf "\n"
        e_error "Error: npm not found."
        printf "Aborting...\n"
        exit
    fi

}

# Test if an npm package exists
npm_pkg_exists() {
	if $(npm list -g $1 > /dev/null 2>&1) || $(npm list $1 > /dev/null 2>&1)  ; then
		return 0
	fi

	return 1
}
