#!/bin/zsh

# Install providers used by nvim
install_nvim_providers() {
	# Python3 provider
	if command_exists python3; then
		if ! python3 -m pip install pynvim; then
			e_error "Error installing pynvim"
		fi
	fi

	# Node.js provider
	if command_exists npm; then
		if ! npm install -g neovim; then
			e_error "Error installing neovim node.js provider"
		fi
	fi
}
